# Generated by Django 6.0.3 on 2026-03-17 21:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('doi', models.CharField(blank=True, max_length=128, null=True)),
                ('journal', models.CharField(blank=True, max_length=255, null=True)),
                ('article_type', models.CharField(blank=True, max_length=255, null=True)),
                ('received_date', models.CharField(blank=True, max_length=32, null=True)),
                ('accepted_date', models.CharField(blank=True, max_length=32, null=True)),
                ('published_date', models.CharField(blank=True, max_length=32, null=True)),
                ('citations_count', models.IntegerField(default=0)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('metadata_raw', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_index', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('doi', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.URLField(blank=True, max_length=1024, null=True)),
                ('pmid', models.CharField(blank=True, max_length=64, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='kg.document')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('path', models.CharField(blank=True, default='', max_length=1024)),
                ('level', models.IntegerField(default=1)),
                ('parent_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('page_numbers', models.JSONField(blank=True, default=list)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='kg.document')),
            ],
        ),
        migrations.CreateModel(
            name='SectionCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_mentions', to='kg.reference')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='kg.section')),
            ],
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_label', models.CharField(max_length=255)),
                ('predicate_label', models.CharField(max_length=255)),
                ('object_label', models.CharField(max_length=255)),
                ('subject_norm', models.CharField(max_length=255)),
                ('predicate_norm', models.CharField(max_length=255)),
                ('object_norm', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=1024, unique=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('support_count', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['subject_norm'], name='kg_triple_subject_66a2f5_idx'), models.Index(fields=['predicate_norm'], name='kg_triple_predica_ae50aa_idx'), models.Index(fields=['object_norm'], name='kg_triple_object__ff0057_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripleEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0)),
                ('source_method', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triple_evidence', to='kg.document')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triple_evidence', to='kg.section')),
                ('triple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='kg.triple')),
            ],
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['document', 'ref_index'], name='kg_referenc_documen_6de83b_idx'),
        ),
        migrations.AddConstraint(
            model_name='sectioncitation',
            constraint=models.UniqueConstraint(fields=('section', 'reference'), name='unique_section_reference_citation'),
        ),
        migrations.AddIndex(
            model_name='tripleevidence',
            index=models.Index(fields=['document', 'triple'], name='kg_tripleev_documen_1c734c_idx'),
        ),
    ]
