# Generated by Django 6.0.3 on 2026-03-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='citations_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='citations_reference_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='number_of_citations',
            field=models.IntegerField(default=0),
        ),
    ]
