# Generated by Django 6.0.3 on 2026-04-24 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0003_triple_conf_support_id_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(choices=[('default', 'Default'), ('custom', 'Custom')], default='custom', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='blacklists/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(choices=[('default', 'Default'), ('custom', 'Custom')], default='custom', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('default_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(choices=[('default', 'Default'), ('custom', 'Custom')], default='custom', max_length=16)),
                ('is_enabled', models.BooleanField(default=True)),
                ('source_path', models.CharField(blank=True, default='', max_length=1024)),
                ('file', models.FileField(blank=True, null=True, upload_to='ontologies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('exact_match', models.BooleanField(default=False)),
                ('subject', models.BooleanField(default=True)),
                ('object', models.BooleanField(default=True)),
                ('default_exact_match', models.BooleanField(default=False)),
                ('default_subject', models.BooleanField(default=True)),
                ('default_object', models.BooleanField(default=True)),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='kg.blacklist')),
            ],
            options={
                'ordering': ['term', 'id'],
                'indexes': [models.Index(fields=['blacklist', 'category'], name='kg_blacklis_blackli_36b008_idx')],
                'constraints': [models.UniqueConstraint(fields=('blacklist', 'term', 'category'), name='unique_blacklist_term_category')],
            },
        ),
        migrations.CreateModel(
            name='EntityLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_labels', to='kg.labellist')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('label_list', 'label'), name='unique_label_list_entity_label')],
            },
        ),
        migrations.CreateModel(
            name='RelationLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('label_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_labels', to='kg.labellist')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('label_list', 'label'), name='unique_label_list_relation_label')],
            },
        ),
    ]
