"""
Post-processing filters for triples generated by the pipeline.
"""

import re
from typing import Iterable

from pipeline_types import Triple


# Special characters that disqualify an entity / predicate from being
# a meaningful term.
SPECIAL_ENTITY_CHARS = [
    "%", "±", "(", ")", "[", "]", "{", "}", "<", ">", "=", "*", "+", "≤", "≥",
]


# English stopword list
ENGLISH_STOPWORDS: frozenset[str] = frozenset({
    "behind", "among", "become", "next", "you", "call", "somehow", "already",
    "unless", "go", "below", "that", "everything", "never", "‘re", "something",
    "or", "upon", "‘ve", "up", "most", "above", "sixty", "more", "fifteen",
    "against", "where", "seemed", "nevertheless", "’s", "she", "using", "’re",
    "often", "of", "nor", "part", "anyone", "make", "say", "when", "do",
    "side", "various", "‘s", "'ll", "both", "than", "yourselves", "down",
    "must", "whereby", "anything", "meanwhile", "be", "yourself", "nine",
    "'m", "much", "if", "very", "am", "least", "throughout", "still",
    "hereafter", "how", "made", "except", "and", "amongst", "will", "’ve",
    "every", "such", "by", "whenever", "those", "used", "our", "at", "latter",
    "during", "re", "’m", "ourselves", "until", "eleven", "four", "own",
    "had", "moreover", "seem", "ten", "what", "hence", "them", "only",
    "afterwards", "on", "have", "so", "around", "latterly", "within", "top",
    "whose", "everyone", "thereby", "else", "somewhere", "him", "even",
    "thus", "these", "however", "an", "a", "’d", "because", "sometime",
    "towards", "another", "onto", "serious", "doing", "elsewhere", "can",
    "ever", "'ve", "should", "twenty", "again", "two", "enough", "fifty",
    "n’t", "hereupon", "other", "her", "done", "yet", "has", "for", "hereby",
    "alone", "anyway", "always", "full", "the", "whereafter", "could", "put",
    "myself", "together", "take", "may", "from", "regarding", "whoever",
    "whole", "thereupon", "which", "beforehand", "whither", "were", "any",
    "beyond", "many", "would", "too", "it", "your", "anywhere", "about",
    "everywhere", "'s", "'d", "others", "my", "under", "less", "why",
    "sometimes", "became", "besides", "few", "becoming", "with", "between",
    "n‘t", "move", "some", "we", "into", "whereas", "wherever", "‘d", "all",
    "each", "beside", "out", "there", "whence", "been", "show", "give",
    "also", "itself", "namely", "its", "empty", "though", "then", "ca",
    "anyhow", "please", "across", "last", "did", "being", "whom", "before",
    "off", "see", "nobody", "cannot", "does", "i", "three", "n't", "someone",
    "here", "just", "might", "perhaps", "seeming", "‘ll", "get", "in",
    "whether", "ours", "without", "through", "otherwise", "therefore",
    "themselves", "noone", "not", "now", "their", "along", "although", "via",
    "wherein", "thence", "who", "really", "yours", "third", "either", "seems",
    "six", "mostly", "neither", "back", "nowhere", "but", "indeed", "keep",
    "almost", "bottom", "mine", "are", "since", "is", "becomes", "one", "was",
    "hers", "rather", "me", "’ll", "therein", "whereupon", "hundred", "same",
    "herself", "his", "formerly", "to", "amount", "once", "whatever", "after",
    "over", "quite", "toward", "nothing", "eight", "forty", "former", "no",
    "twelve", "herein", "this", "he", "himself", "while", "‘m", "thru", "per",
    "front", "further", "several", "us", "five", "first", "name",
    "thereafter", "'re", "they", "as", "due", "none", "well",
})


# ---------------------------------------------------------------------------
# Deduplication
# ---------------------------------------------------------------------------

def remove_duplicates(triples: list[Triple]) -> list[Triple]:
    """
    Remove duplicates, keeping the first (highest-confidence) occurrence.
    Boost the confidence of the existing triple by 0.001 for each duplicate
    so a triple repeated 3 times receives +0.003 confidence.
    """
    seen: set[tuple[str, str, str]] = set()
    unique: list[Triple] = []
    for t in triples:
        key = (t.sub, t.pred, t.obj)
        if key not in seen:
            seen.add(key)
            unique.append(t)
        else:
            existing_index = next(
                i for i, u in enumerate(unique)
                if u.sub == key[0] and u.pred == key[1] and u.obj == key[2]
            )
            existing = unique[existing_index]
            unique[existing_index] = existing._replace(
                conf=min(existing.conf + 0.001, 1.0)
            )
    return unique


# ---------------------------------------------------------------------------
# Validity / blacklist matching
# ---------------------------------------------------------------------------

def is_invalid_string(text: str) -> bool:
    """
    Return True when a string is an invalid entity or predicate (too short,
    contains a number, or contains a disallowed special character).
    """
    normalized = text.replace("_", " ").strip().lower()
    if len(normalized) < 3:
        return True
    if re.search(r"\d+(\.\d+)?%?", normalized):
        return True
    if any(char in normalized for char in SPECIAL_ENTITY_CHARS):
        return True
    return False


def normalize_blacklist_entity(text: str) -> str:
    return text.strip().replace(" ", "_").lower()


def match_entity_string(text: str, blacklist: list[str]) -> bool:
    """
    Substring match of text against any term in blacklist (case-insensitive).
    """
    text_norm = normalize_blacklist_entity(text)
    for substring in blacklist:
        if normalize_blacklist_entity(substring) in text_norm:
            return True
    return False


def match_entity_exact(text: str, blacklist: list[str]) -> bool:
    """
    Exact match of text against any term in blacklist (case-insensitive).
    """
    text_norm = normalize_blacklist_entity(text)
    for term in blacklist:
        if text_norm == normalize_blacklist_entity(term):
            return True
    return False


def match_stopwords(text: str, stopwords: Iterable[str]) -> bool:
    """Exact (lowercase) match of text against the stopwords iterable."""
    return text.strip().lower() in stopwords


def filter_triples(
    triples: list[Triple],
    blacklist_sets: tuple[list[str], list[str], list[str], list[str]],
    stopwords: Iterable[str] | None = None,
) -> list[Triple]:
    """
    Drop triples that are invalid (is_invalid_string), composed of a
    stopword subject/object, or matched by any of the four blacklist
    rule buckets:
      (subject_excl_str, object_excl_str, subject_excl_word, object_excl_word).
    """
    result: list[Triple] = []
    subject_excl_str, object_excl_str, subject_excl_word, object_excl_word = blacklist_sets
    if stopwords is None:
        stopword_set: frozenset[str] | set[str] = ENGLISH_STOPWORDS
    elif isinstance(stopwords, (set, frozenset)):
        stopword_set = stopwords
    else:
        stopword_set = set(stopwords)
    for triple in triples:
        if (
            is_invalid_string(triple.sub)
            or is_invalid_string(triple.pred)
            or is_invalid_string(triple.obj)
        ):
            continue
        if match_stopwords(triple.sub, stopword_set) or match_stopwords(triple.obj, stopword_set):
            continue
        if match_entity_string(triple.sub, subject_excl_str) or match_entity_string(triple.obj, object_excl_str):
            continue
        if match_entity_exact(triple.sub, subject_excl_word) or match_entity_exact(triple.obj, object_excl_word):
            continue
        result.append(triple)
    return result


# ---------------------------------------------------------------------------
# Ontology-aware confidence boosting
# ---------------------------------------------------------------------------

class OntologyFilter:
    """
    Boost the confidence of triples whose subject/object matches a known
    ontology term, optionally dropping triples without any match.
    """

    def __init__(self, terms: Iterable[str]):
        self.terms: frozenset[str] = (
            terms if isinstance(terms, frozenset) else frozenset(terms)
        )

    def normalize(self, text: str) -> str:
        return text.replace("_", " ").lower()

    def matches(self, text: str) -> bool:
        return self.normalize(text) in self.terms

    def boost(
        self,
        triples: list[Triple],
        boost_amount: float = 0.05,
        require_match: bool = False,
    ) -> list[Triple]:
        result: list[Triple] = []
        for t in triples:
            sub_match = self.matches(t.sub)
            obj_match = self.matches(t.obj)

            if require_match and not (sub_match or obj_match):
                continue

            new_conf = t.conf
            if sub_match:
                new_conf = min(new_conf + boost_amount, 1.0)
            if obj_match:
                new_conf = min(new_conf + boost_amount, 1.0)

            result.append(t._replace(conf=new_conf))

        return result
